### ISSUE TITLE
investigate whether we are properly tracking existing users

### ISSUE THREAD

**Issue by devoncarew** [GoogleChrome/chromedeveditor#3415]
Our analytics seem to say that our new user count ~= to our existing user count, which seems odd. Are we properly tracking existing users?
- [x] What user ID is currently being used for tracking?
- [x] Are we generating & setting the user ID ourselves? eg. via [`gaTracker.set('userId',myUserid);`](https://github.com/GoogleChrome/chrome-platform-analytics/issues/9) or is CPA doing this for us?
- [x] Identify user ID persistence (chrome.storage?) and ensure it's persisting across sessions
- [x] Ensure persistence of UUID after upgrading to new version of app from WebStore
- [x] Confirm app delete & reinstall gives a new UUID
- [x] Confirm app disable & reenable keeps same UUID
- [x] Is tracking currently enabled by default in local development? (_sure is!  simply bound to About checkbox_)
- [x] Update issue
### Notes
- Check the user Id `var key = "google-analytics.analytics.user-id"; chrome.storage.local.get(key, function(result) { console.log(result[key]) })`
- Generated by [CPA ServiceSettings](https://github.com/GoogleChrome/chrome-platform-analytics/blob/ef625827ae6c14269c26a79110ac8c8fd2172d9e/src/internal/service_settings.js#L242-L254)
- CPA is POSTing this properly as our [Client ID](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cid) 
- Should we disable tracking for local development and tests?  do we send different dimensions to distinguish CDE devs (incl forks) & drone.io runs from real end-users of the published app?
